CREATE TABLE `wechat_favorite_info` (
  `ID_WECHAT_FAVORITE_INFO` int(11) NOT NULL AUTO_INCREMENT,
  `HASH` varchar(32) NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `DATE_CREATED` datetime NOT NULL,
  `DATE_UPDATED` datetime NOT NULL,
  PRIMARY KEY (`ID_WECHAT_FAVORITE_INFO`)
) ENGINE=InnoDB AUTO_INCREMENT=74 DEFAULT CHARSET=utf8;

CREATE TABLE `wechat_favorite_tag` (
  `ID_WECHAT_FAVORITE_TAG` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(32) NOT NULL,
  `ID_WECHAT_FAVORITE_INFO` int(11) NOT NULL,
  `DATE_UPDATED` datetime NOT NULL,
  `DATE_CREATED` datetime NOT NULL,
  PRIMARY KEY (`ID_WECHAT_FAVORITE_TAG`)
) ENGINE=InnoDB AUTO_INCREMENT=74 DEFAULT CHARSET=utf8;